# Generated by Django 5.2.5 on 2025-08-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
